name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential zlibc libgmp-dev openssl libssl-dev
        sudo apt-get install libpth-dev scons
        sudo apt-get install clang
    - name: Build with ${{ matrix.cc }}
      run: CC=${{ matrix.cc }}  scons