name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libcmocka-dev git gettext autopoint
        sudo apt-get install libjson-c-dev libreadline-dev libsodium-dev
        sudo apt-get install clang
    - name: Build with ${{ matrix.cc }}
      run: |
        autoreconf -i -f
        CC=${{ matrix.cc }} ./configure
        CC=${{ matrix.cc }} make

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install test dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install build-essential libcmocka-dev git gettext autopoint
          sudo apt-get install libjson-c-dev libreadline-dev libsodium-dev
      - name: Build and run tests
        run: |
          autoreconf -i -f
          ./configure --enable-debug --enable-asan --enable-ubsan
          make check
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

