name: Documentation

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout
      
      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install build-essential

      - name: Generate files
        run: |
          autoreconf -i -f
          ./configure

      - uses: mattnotmitt/doxygen-action@v1 
        name: Generate documentation
        with:
          doxyfile-path: doc/Doxyfile

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html
          cname: doc.netsukuku.net
